### ISSUE TITLE
agent_in_radius function must behave differently

### ISSUE THREAD

**Issue by Kubasinska** [LABSS/PyPROTON-OC#29]
https://github.com/LABSS/PyPROTON-OC/blob/c547d45bbf911572cb964eaabfcfc42d43a5cb7b/protonoc/simulator/entities.py#L482-L500

if I ask for agents in radius 2, the function returns a set with radius 1 and radius 2 agents. This does not emulate the behaviour of the function in NetLogo. We need to exclude agents at a lower radius than those requested. This does not create errors just increases the number of agents to compute on.

**Comment by mariopaolucci** [comment]
Actually, the netlogo snipped takes care in line of the lower rings, taking only agents precisely at the needed distance: `] (turtle-set nw:turtles-in-radius d nw:turtles-in-reverse-radius d) with [ nw:distance-to myself = d ]---'.  This would be expensive if we looked farther, but our ranges are always small.

If we want a different system, we better change the name. Also, this funcionality was already implemented - and I think quite efficiently - in (https://github.com/LABSS/PyPROTON-OC/blob/0874784fd2dfabcbf9fd72e8c16f7a123ad66454/protonoc/simulator/extra.py#L51). Maybe we should first of all expand on that, and then create the needed function "exactly distance d".
